ubuntu:
  image: ubuntu:14.04
  links:
    - picomto_db:db
  ports:
    - 8080:80
picomto_db:
  image: mysql/mysql-server
  environment:
    MYSQL_ROOT_PASSWORD: picomto_root_passwd
phpmyadmin:
  image: phpmyadmin/phpmyadmin
  links:
    - picomto_db:db
  ports:
    - 8181:80
  environment:
    MYSQL_USERNAME: root
    MYSQL_ROOT_PASSWORD: picomto_root_passwd